# IMPORTANT: if you change this file, remember to edit doc/requirements.txt as
# well
name: ploomber-docs

channels:
  - conda-forge

dependencies:
  - python=3.9
  - tree
  - pip
  - psycopg2
  - pandoc
  - pip:
    # needed for the examples
    - joblib
    - scikit-learn
    - seaborn
    - mistune<2

    # for converting notebooks
    - nbsphinx

    # for the toggle  button
    - sphinx-toolbox

    # https://github.com/spatialaudio/nbsphinx/issues/584
    - sphinx==7.0.0
    # for plotting
    - pygraphviz

    # for running notebooks from the projects repo
    - papermill
    - jupytext
    - ipywidgets

    # install ploomber
    - -e ..
